Started program at  12:47:04
Command history can't be saved outside of IPython/Jupyter
Started program at  12:57:24
Command history can't be saved outside of IPython/Jupyter
Started program at  13:04:22
Command history can't be saved outside of IPython/Jupyter
Program exited at 13:04:26
Started program at  13:04:30
Command history can't be saved outside of IPython/Jupyter
Program exited at 13:04:38
Started program at  14:02:02
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:02:05
Started program at  14:02:11
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:02:35
Started program at  14:06:35
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:08:00
Started program at  14:08:06
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:08:23
Started program at  14:08:28
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:08:53
Started program at  14:17:07
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:17:24
Started program at  14:18:00
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:18:10
Started program at  14:34:48
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:35:00
Started program at  14:36:55
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:37:56
Started program at  14:45:19
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:45:33
Started program at  14:54:33
Traceback (most recent call last):
  File "/home/mamba/Documents/Repos/DO_Lab2DSweeps/GUI_Measureit.py", line 1107, in <module>
    main()
  File "/home/mamba/Documents/Repos/DO_Lab2DSweeps/GUI_Measureit.py", line 1100, in main
    window = UImain()
             ^^^^^^^^
  File "/home/mamba/Documents/Repos/DO_Lab2DSweeps/GUI_Measureit.py", line 99, in __init__
    self.start_logs()
  File "/home/mamba/Documents/Repos/DO_Lab2DSweeps/GUI_Measureit.py", line 289, in start_logs
    start_all_logging()
  File "/home/mamba/.local/lib/python3.12/site-packages/qcodes/logger/logger.py", line 379, in start_all_logging
    start_command_history_logger()
  File "/home/mamba/.local/lib/python3.12/site-packages/qcodes/logger/logger.py", line 342, in start_command_history_logger
    from IPython import get_ipython  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mamba/.local/lib/python3.12/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/home/mamba/.local/lib/python3.12/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core import release, crashhandler
  File "/home/mamba/.local/lib/python3.12/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/mamba/.local/lib/python3.12/site-packages/IPython/core/ultratb.py", line 108, in <module>
    import IPython.utils.colorable as colorable
  File "/home/mamba/.local/lib/python3.12/site-packages/IPython/utils/colorable.py", line 20, in <module>
    class Colorable(Configurable):
  File "/home/mamba/.local/lib/python3.12/site-packages/traitlets/traitlets.py", line 963, in __new__
    return super().__new__(mcls, name, bases, classdict, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Started program at  14:56:40
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:58:13
Started program at  14:58:34
Command history can't be saved outside of IPython/Jupyter
Program exited at 14:58:37
Started program at  15:00:07
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:00:11
Started program at  15:00:18
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:00:28
Started program at  15:04:46
Command history can't be saved outside of IPython/Jupyter
Started program at  15:04:57
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:05:17
Started program at  15:05:47
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:06:21
Started program at  15:06:33
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:06:41
Started program at  15:07:18
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:07:22
Started program at  15:07:28
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:07:36
Started program at  15:09:31
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:09:54
Started program at  15:10:54
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:10:57
Started program at  15:19:11
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:19:42
Started program at  15:20:12
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:20:15
Started program at  15:20:20
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:20:24
Started program at  15:22:26
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:22:36
Started program at  15:23:45
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:23:54
Started program at  15:24:10
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:24:20
Started program at  15:27:07
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:27:41
Started program at  15:28:57
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:29:03
Started program at  15:32:01
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:33:29
Started program at  15:36:10
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:36:20
Started program at  15:53:45
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:53:55
Started program at  15:54:59
Command history can't be saved outside of IPython/Jupyter
Program exited at 15:55:08
Started program at  15:55:28
Command history can't be saved outside of IPython/Jupyter
Program exited at 16:01:40
Started program at  21:45:53
Command history can't be saved outside of IPython/Jupyter
Program exited at 21:46:19
